/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.project.demo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Product service. Represents a row in the &quot;Shopping_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.project.demo.model.impl.ProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.project.demo.model.impl.ProductImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Product
 * @generated
 */
@ProviderType
public interface ProductModel extends BaseModel<Product> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product.
	 *
	 * @return the uuid of this product
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this product.
	 *
	 * @param uuid the uuid of this product
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this product.
	 *
	 * @return the ID of this product
	 */
	public long getId();

	/**
	 * Sets the ID of this product.
	 *
	 * @param id the ID of this product
	 */
	public void setId(long id);

	/**
	 * Returns the product name of this product.
	 *
	 * @return the product name of this product
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product.
	 *
	 * @param productName the product name of this product
	 */
	public void setProductName(String productName);

	/**
	 * Returns the color of this product.
	 *
	 * @return the color of this product
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this product.
	 *
	 * @param color the color of this product
	 */
	public void setColor(String color);

	/**
	 * Returns the rating count of this product.
	 *
	 * @return the rating count of this product
	 */
	public long getRatingCount();

	/**
	 * Sets the rating count of this product.
	 *
	 * @param ratingCount the rating count of this product
	 */
	public void setRatingCount(long ratingCount);

	/**
	 * Returns the rating of this product.
	 *
	 * @return the rating of this product
	 */
	public double getRating();

	/**
	 * Sets the rating of this product.
	 *
	 * @param rating the rating of this product
	 */
	public void setRating(double rating);

	/**
	 * Returns the price of this product.
	 *
	 * @return the price of this product
	 */
	public long getPrice();

	/**
	 * Sets the price of this product.
	 *
	 * @param price the price of this product
	 */
	public void setPrice(long price);

	/**
	 * Returns the discount of this product.
	 *
	 * @return the discount of this product
	 */
	public int getDiscount();

	/**
	 * Sets the discount of this product.
	 *
	 * @param discount the discount of this product
	 */
	public void setDiscount(int discount);

	/**
	 * Returns the final price of this product.
	 *
	 * @return the final price of this product
	 */
	public long getFinalPrice();

	/**
	 * Sets the final price of this product.
	 *
	 * @param finalPrice the final price of this product
	 */
	public void setFinalPrice(long finalPrice);

	/**
	 * Returns the gender of this product.
	 *
	 * @return the gender of this product
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this product.
	 *
	 * @param gender the gender of this product
	 */
	public void setGender(String gender);

	/**
	 * Returns the product count of this product.
	 *
	 * @return the product count of this product
	 */
	public int getProductCount();

	/**
	 * Sets the product count of this product.
	 *
	 * @param productCount the product count of this product
	 */
	public void setProductCount(int productCount);

	/**
	 * Returns the status of this product.
	 *
	 * @return the status of this product
	 */
	public int getStatus();

	/**
	 * Sets the status of this product.
	 *
	 * @param status the status of this product
	 */
	public void setStatus(int status);

	/**
	 * Returns the create date of this product.
	 *
	 * @return the create date of this product
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this product.
	 *
	 * @param createDate the create date of this product
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product.
	 *
	 * @return the modified date of this product
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product.
	 *
	 * @param modifiedDate the modified date of this product
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Product> toCacheModel();

	@Override
	public Product toEscapedModel();

	@Override
	public Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}